// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAppDataDir() {
    return $Call.ByID(3971836095);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCacheDir() {
    return $Call.ByID(2657066464);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultCookie() {
    return $Call.ByID(696262752);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultUserAgent() {
    return $Call.ByID(3451079734);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDownloadsDir() {
    return $Call.ByID(2920978241);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetOutputDir() {
    return $Call.ByID(911157087);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetPlatform() {
    return $Call.ByID(3326752422);
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function PickDir(title) {
    return $Call.ByID(544703537, title);
}

/**
 * @returns {$CancellablePromise<$models.Config | null>}
 */
export function ReadConfig() {
    return $Call.ByID(1074585641).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.Config | null} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(config) {
    return $Call.ByID(2383596460, config);
}

/**
 * @param {string} cookie
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultCookie(cookie) {
    return $Call.ByID(3289522124, cookie);
}

/**
 * @param {string} userAgent
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultUserAgent(userAgent) {
    return $Call.ByID(57529906, userAgent);
}

/**
 * @param {string} outputDir
 * @returns {$CancellablePromise<void>}
 */
export function SetOutputDir(outputDir) {
    return $Call.ByID(4061964979, outputDir);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
