// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFile(path) {
    return $Call.ByID(633513800, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.DownloadedFile[]>}
 */
export function GetFiles(path) {
    return $Call.ByID(758892482, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function ShareFile(path) {
    return $Call.ByID(4195080730, path);
}

// Private type creation functions
const $$createType0 = $models.DownloadedFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
