// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("outputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputDir"] = "";
        }
        if (!("defaultCookie" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultCookie"] = "";
        }
        if (!("defaultUserAgent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultUserAgent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class HyperDownloadError {
    /**
     * Creates a new HyperDownloadError instance.
     * @param {Partial<HyperDownloadError>} [$$source = {}] - The source object to create the HyperDownloadError.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HyperDownloadError instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HyperDownloadError}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HyperDownloadError(/** @type {Partial<HyperDownloadError>} */($$parsedSource));
    }
}

export class HyperDownloadTask {
    /**
     * Creates a new HyperDownloadTask instance.
     * @param {Partial<HyperDownloadTask>} [$$source = {}] - The source object to create the HyperDownloadTask.
     */
    constructor($$source = {}) {
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("outputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputDir"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("fileSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileSize"] = 0;
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }
        if (!("stopped" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["stopped"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HyperDownloadTask instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HyperDownloadTask}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HyperDownloadTask(/** @type {Partial<HyperDownloadTask>} */($$parsedSource));
    }
}

export class HyperDownloadTasksSnapshot {
    /**
     * Creates a new HyperDownloadTasksSnapshot instance.
     * @param {Partial<HyperDownloadTasksSnapshot>} [$$source = {}] - The source object to create the HyperDownloadTasksSnapshot.
     */
    constructor($$source = {}) {
        if (!("tasks" in $$source)) {
            /**
             * @member
             * @type {HyperDownloadTask[]}
             */
            this["tasks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HyperDownloadTasksSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HyperDownloadTasksSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField0_0($$parsedSource["tasks"]);
        }
        return new HyperDownloadTasksSnapshot(/** @type {Partial<HyperDownloadTasksSnapshot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = HyperDownloadTask.createFrom;
const $$createType1 = $Create.Array($$createType0);
