// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(3601566522);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Maximise() {
    return $Call.ByID(1421775801);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Minimise() {
    return $Call.ByID(1882376179);
}
