// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as hyperDownload$0 from "../../../../../hyperion-downloader/services/hyperDownload/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "downloadCompleted": hyperDownload$0.HyperDownloadTask | null;
            "downloadError": hyperDownload$0.HyperDownloadError;
            "fileUpdate": string;
            "tasksSnapshot": hyperDownload$0.HyperDownloadTasksSnapshot;
        }
    }
}
