//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hyperDownload$0 from "../../../../../hyperion-downloader/services/hyperDownload/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "downloadCompleted": $$createType1,
        "downloadError": $$createType2,
        "tasksSnapshot": $$createType3,
    }));
}

// Private type creation functions
const $$createType0 = hyperDownload$0.HyperDownloadTask.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = hyperDownload$0.HyperDownloadError.createFrom;
const $$createType3 = hyperDownload$0.HyperDownloadTasksSnapshot.createFrom;

configure();
