// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HyperDownloadAdvancedOptions {
    /**
     * Creates a new HyperDownloadAdvancedOptions instance.
     * @param {Partial<HyperDownloadAdvancedOptions>} [$$source = {}] - The source object to create the HyperDownloadAdvancedOptions.
     */
    constructor($$source = {}) {
        if (!("cookies" in $$source)) {
            /**
             * Cookies to include in the download request, formatted as a single string (e.g. "key1=value1; key2=value2")
             * @member
             * @type {string}
             */
            this["cookies"] = "";
        }
        if (!("userAgent" in $$source)) {
            /**
             * User-Agent string to include in the download request
             * @member
             * @type {string}
             */
            this["userAgent"] = "";
        }
        if (!("referer" in $$source)) {
            /**
             * Referer URL to include in the download request
             * @member
             * @type {string}
             */
            this["referer"] = "";
        }
        if (!("authorizationHeader" in $$source)) {
            /**
             * Value for the Authorization header to include in the download request (e.g. "Bearer <token>")
             * @member
             * @type {string}
             */
            this["authorizationHeader"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HyperDownloadAdvancedOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HyperDownloadAdvancedOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HyperDownloadAdvancedOptions(/** @type {Partial<HyperDownloadAdvancedOptions>} */($$parsedSource));
    }
}
