// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAppDataDir() {
    return $Call.ByID(3327466064);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCacheDir() {
    return $Call.ByID(3634806983);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultCookie() {
    return $Call.ByID(2394006225);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultUserAgent() {
    return $Call.ByID(1586852197);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDownloadsDir() {
    return $Call.ByID(3253954786);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetOutputDir() {
    return $Call.ByID(2366844882);
}

/**
 * @returns {$CancellablePromise<$models.PlatformInfo>}
 */
export function GetPlatformInfo() {
    return $Call.ByID(1149989297).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function PickDir(title) {
    return $Call.ByID(392576982, title);
}

/**
 * @returns {$CancellablePromise<$models.Config | null>}
 */
export function ReadConfig() {
    return $Call.ByID(3397071224).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.Config | null} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(config) {
    return $Call.ByID(2592737649, config);
}

/**
 * @param {string} cookie
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultCookie(cookie) {
    return $Call.ByID(3465788365, cookie);
}

/**
 * @param {string} userAgent
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultUserAgent(userAgent) {
    return $Call.ByID(995178897, userAgent);
}

/**
 * @param {string} outputDir
 * @returns {$CancellablePromise<void>}
 */
export function SetOutputDir(outputDir) {
    return $Call.ByID(2352653830, outputDir);
}

// Private type creation functions
const $$createType0 = $models.PlatformInfo.createFrom;
const $$createType1 = $models.Config.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
