// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hyperStructs$0 from "../../internal/pkg/hyperStructs/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} uid
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTask(uid) {
    return $Call.ByID(3542767808, uid);
}

/**
 * @param {string} url
 * @param {string} outputDir
 * @param {string} tempDir
 * @param {number} concurrentDownloads
 * @param {number} targetPartSize
 * @param {hyperStructs$0.HyperDownloadAdvancedOptions | null} advancedOptions
 * @returns {$CancellablePromise<void>}
 */
export function DownloadFile(url, outputDir, tempDir, concurrentDownloads, targetPartSize, advancedOptions) {
    return $Call.ByID(1480043384, url, outputDir, tempDir, concurrentDownloads, targetPartSize, advancedOptions);
}

/**
 * @returns {$CancellablePromise<$models.HyperDownloadTask[]>}
 */
export function GetTasks() {
    return $Call.ByID(1098437092).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} uid
 * @returns {$CancellablePromise<void>}
 */
export function PauseTask(uid) {
    return $Call.ByID(3605496725, uid);
}

/**
 * @param {string} uid
 * @returns {$CancellablePromise<void>}
 */
export function StopTask(uid) {
    return $Call.ByID(1043459043, uid);
}

// Private type creation functions
const $$createType0 = $models.HyperDownloadTask.createFrom;
const $$createType1 = $Create.Array($$createType0);
