name: Nightly Android

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Checkout Wails v3
              run: git clone --depth 1 https://github.com/wailsapp/wails.git ../wails

            - name: Install Linux Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-4-dev libwebkitgtk-6.0-dev build-essential pkg-config

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Setup Android Command Line Tools
              uses: android-actions/setup-android@v4
              with:
                  packages: ""

            - name: Setup Android SDK
              run: |
                  yes | sdkmanager --licenses
                  sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;26.3.11579264"

            - name: Setup Go
              uses: actions/setup-go@v6
              with:
                  go-version: "1.26" # Update to your specific Go version if needed
                  cache: true

            - name: Setup pnpm
              uses: pnpm/action-setup@v6
              with:
                  version: latest

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"
                  cache: "pnpm"
                  cache-dependency-path: frontend/pnpm-lock.yaml

            - name: Install Frontend Dependencies
              run: |
                  cd frontend
                  pnpm ci

            - name: Install Wails v3 CLI
              run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

            - name: Build Application (Android)
              run: |
                  export ANDROID_HOME=$HOME/Android/Sdk
                  export PATH=$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
                  export CC=$ANDROID_HOME/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
                  export CXX=$ANDROID_HOME/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
                  export CGO_ENABLED=1
                  wails3 task android:package:fat

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: hyperion-downloader-android
                  path: |
                      build/android/app/build/outputs/apk/release/app-release.apk
